# Generated by Django 5.2.7 on 2025-10-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='usersubmission',
            index=models.Index(fields=['-created_at'], name='predictor_u_created_b84f74_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubmission',
            index=models.Index(fields=['user', '-created_at'], name='predictor_u_user_id_0e94f7_idx'),
        ),
    ]
