# Generated by Django 5.2.7 on 2025-10-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_usersubmission_ip_address_usersubmission_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
