# Generated by Django 5.2.7 on 2025-10-19 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_usersubmission_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
