# Generated by Django 5.2.7 on 2025-10-19 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_alter_usersubmission_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='predicted_disease',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='diet',
            field=models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan'), ('MIXED', 'Mixed')], max_length=20),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='exercise_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='existing_diseases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='primary_prediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_submissions', to='predictor.disease'),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='sleep_hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='stress_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='travel_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rank', models.IntegerField(default=1)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.disease')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_diseases', to='predictor.usersubmission')),
            ],
            options={
                'ordering': ['-confidence_score'],
                'unique_together': {('submission', 'disease')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('duration', models.CharField(help_text="e.g., '3 days', '1 week'", max_length=50)),
                ('onset', models.CharField(choices=[('SUDDEN', 'Sudden'), ('GRADUAL', 'Gradual')], max_length=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_symptoms', to='predictor.usersubmission')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.symptom')),
            ],
            options={
                'unique_together': {('submission', 'symptom')},
            },
        ),
    ]
